name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout esp32_blink repo
      uses: actions/checkout@v2
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32s3
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: 
          build/blink.bin
